<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <Version>2.2.2</Version>
    <UserSecretsId>dotnet-UVOCBot-BCEF48FF-ADA7-4525-8513-6E65E0B7D897</UserSecretsId>
    <Authors>Carl Stephens</Authors>
  </PropertyGroup>
  
  <!-- Docker Support -->
  <PropertyGroup>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <IsPublishable>true</IsPublishable>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>uvocbot</ContainerRepository>
    <ContainerFamily>alpine</ContainerFamily>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Remora.Discord" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.ApexLegends\UVOCBot.Plugins.ApexLegends.csproj" />
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.Feeds\UVOCBot.Plugins.Feeds.csproj" />
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.Greetings\UVOCBot.Plugins.Greetings.csproj" />
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.Planetside\UVOCBot.Plugins.Planetside.csproj" />
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.Roles\UVOCBot.Plugins.Roles.csproj" />
    <ProjectReference Include="..\Plugins\UVOCBot.Plugins.SpaceEngineers\UVOCBot.Plugins.SpaceEngineers.csproj" />
    <ProjectReference Include="..\UVOCBot.Discord.Core\UVOCBot.Discord.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>
</Project>
