<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="carlst99.Mandible" Version="6.0.0" />
    <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UVOCBot.Discord.Core\UVOCBot.Discord.Core.csproj" />
  </ItemGroup>

</Project>
