<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="carlst99.Mandible" />
    <PackageReference Include="CodeHollow.FeedReader" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UVOCBot.Discord.Core\UVOCBot.Discord.Core.csproj" />
  </ItemGroup>

</Project>
