// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UVOCBot.Api;

namespace UVOCBot.Api.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("UVOCBot.Api.Model.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("UVOCBot.Api.Model.GuildTwitterSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("RelayChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId");

                    b.ToTable("GuildTwitterSettings");
                });

            modelBuilder.Entity("UVOCBot.Api.Model.TwitterUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<ulong?>("GuildTwitterSettingsGuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<long?>("LastRelayedTweetId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("GuildTwitterSettingsGuildId");

                    b.ToTable("TwitterUsers");
                });

            modelBuilder.Entity("UVOCBot.Api.Model.TwitterUser", b =>
                {
                    b.HasOne("UVOCBot.Api.Model.GuildTwitterSettings", null)
                        .WithMany("TwitterUsers")
                        .HasForeignKey("GuildTwitterSettingsGuildId");
                });

            modelBuilder.Entity("UVOCBot.Api.Model.GuildTwitterSettings", b =>
                {
                    b.Navigation("TwitterUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
