<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DbgCensus.Core" />
    <PackageReference Include="DbgCensus.EventStream.EventHandlers" />
    <PackageReference Include="DbgCensus.Rest" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UVOCBot.Discord.Core\UVOCBot.Discord.Core.csproj" />
  </ItemGroup>

</Project>
