// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UVOCBot;

namespace UVOCBot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20201202233012_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GuildTwitterSettingsTwitterUser", b =>
                {
                    b.Property<int>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TwitterUsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildsId", "TwitterUsersId");

                    b.HasIndex("TwitterUsersId");

                    b.ToTable("GuildTwitterSettingsTwitterUser");
                });

            modelBuilder.Entity("UVOCBot.Model.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeOfLastTwitterFetch")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("UVOCBot.Model.GuildSettings", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("UVOCBot.Model.GuildTwitterSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RelayChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildTwitterSettings");
                });

            modelBuilder.Entity("UVOCBot.Model.TwitterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TwitterUser");
                });

            modelBuilder.Entity("GuildTwitterSettingsTwitterUser", b =>
                {
                    b.HasOne("UVOCBot.Model.GuildTwitterSettings", null)
                        .WithMany()
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UVOCBot.Model.TwitterUser", null)
                        .WithMany()
                        .HasForeignKey("TwitterUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
